export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
  'abdomen': 'Abdomen',
  'aperturas_en_banco_inclinado_nombre': 'Aperturas en banco inclinado',
  'aperturas_en_banco_inclinado_descripcion': 'Ejercicio básico para entrenar el conjunto del pectoral mayor (primario), deltoides anterior y tríceps (secundarios) y expansión torácica.',
  'aperturas_en_banco_inclinado_paso1': 'Sentado en banco inclinado (no mayor a 60Â°)',
  'aperturas_en_banco_inclinado_paso2': 'Mancuernas en agarre neutro y codos levemente flexionados (Posición inicial)',
  'aperturas_en_banco_inclinado_paso3': 'Abre los brazos hacia los lados, expandiendo el pectoral, hasta el nivel del tronco.',
  'aperturas_en_banco_inclinado_paso4': 'Cierra los brazos hacia arriba, contrayendo el pecho y regresando a la posición inicial.',
  'aperturas_en_banco_inclinado_tips1': 'Realiza una contracción del pectoral al cerrar los brazos, para dar mayor estímulo a este musculo.',
  'aperturas_en_banco_inclinado_tips2': 'Mantén las mancuernas en agarre neutro y los brazos semi-flexionados, para mejor enfoque en el pectoral.',
  'biceps':'Bíceps',
  'bicicletas_nombre': 'Bicicletas',
  'bicicletas_descripcion': 'Ejercicio abdominal (elevación tronco y piernas con rotación), que combina la elevación de tronco y piernas, enfocando el esfuerzo en la zona del recto abdominal, así como en los oblicuos.',
  'bicicletas_paso1': 'Acostado boca arriba, rodillas levemente flexionadas, manos al lado de cabeza y pies elevados',
  'bicicletas_paso2': 'Levantar tronco y pierna, girando el brazo contrario hacia la pierna elevada',
  'bicicletas_paso3': 'Regresar el tronco y la pierna a la posición inicial y realizar el mismo movimiento con brazo/pierna contrarios',
  'bicicletas_tips1': 'Mantenga contraido el abdomen todo el tiempo, así como lograr contracciones en los oblicuos al elevar el tronco',
  'bicicletas_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'bicicletas_tips3': 'Evita el impulso con el tronco y piernas y busca no apoyar los pies en el suelo durante la ejecución del ejercicio',
  'body_height': 'Peso corporal',
  'choise_your_lang': 'Lenguajes disponibles',
  'concentrado_nombre': 'Concentrado',
  'concentrado_descripcion': 'Ejercicio de aislamiento que permite controlar el ejercicio en amplitud, velocidad y movimiento sobre el bíceps y braquial anterior',
  'concentrado_paso1': 'Sentado, mancuerna con agarre en supinación y brazo apoyado sobre la cara interna del muslo.',
  'concentrado_paso2': 'Subir la mancuerna realizando una flexión de codo, hasta el nivel dep pecho.',
  'concentrado_paso3': 'Descender la mancuerna, extendiendo el brazo y regresando a la posición inicial.',
  'concentrado_paso4': 'Una vez finalice la serie con un brazo, realizar el mismo movimiento con el otro.',
  'concentrado_tips1': 'Ejercicio de aislamiento muscular, enfocado en técnica y control del peso.',
  'concentrado_tips2': 'Especial para principiantes e intermedios.',
  'crunches_nombre': 'Crunches',
  'crunches_descripcion': 'Ejercicio que trabaja principalmente el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'crunches_paso1': 'Acostado boca arriba, rodillas flexionadas, pies en el suelo, manos detrás de la cabeza',
  'crunches_paso2': 'Elevar el tronco, curvando levemente la espalda y sin mover la cabeza hacia adelante',
  'crunches_paso3': 'Descender controladamente el tronco hasta regresar a la posición inicial',
  'crunches_tips1': 'Puedes ubicar las manos cruzadas sobre el pecho o hacia adelante (recomendado para principiantes)',
  'crunches_tips2': 'Puedes levantar la punta de los pies y evita el impulso con brazos o espalda',
  'crunches_con_elevacion_de_piernas_nombre': 'Crunches con elevación de piernas',
  'crunches_con_elevacion_de_piernas_descripcion': 'Ejercicio que trabaja principalmente el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'crunches_con_elevacion_de_piernas_paso1': 'Acostado boca arriba, rodillas flexionadas, piernas levantadas, manos al lado de la cabeza',
  'crunches_con_elevacion_de_piernas_paso2': 'Elevar el tronco, curvando levemente la espalda y sin mover la cabeza hacia adelante',
  'crunches_con_elevacion_de_piernas_paso3': 'Descender controladamente el tronca hasta regresar a la posición inicial',
  'crunches_con_elevacion_de_piernas_tips1': 'Puedes ubicar las manos cruzadas sobre el pecho o hacia adelante (recomendado para principiantes)',
  'crunches_con_elevacion_de_piernas_tips2': 'Mantén las piernas fijas en el aire y realiza muchas repeticiones para mayor intensidad muscular',
  'crunches_con_pies_juntos_nombre': 'Crunches con pies juntos',
  'crunches_con_pies_juntos_descripcion': 'Ejercicio que trabaja por completo el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'crunches_con_pies_juntos_paso1': 'Acostado boca arriba, piernas abiertas, juntando las plantas de los pies, manos hacia al frente',
  'crunches_con_pies_juntos_paso2': 'Elevar el tronco completamente, hasta llevar el tronco verticalmente y tomar los pies con las manos',
  'crunches_con_pies_juntos_paso3': 'Recostar de nuevo el tronco sobre la colchoneta, hasta regresar a la posición inicial',
  'crunches_con_pies_juntos_tips1': 'Mantén las plantas de los pies juntos todo el tiempo y en el suelo, para evitar el impulso con las piernas',
  'crunches_con_pies_juntos_tips2': 'Espalda recta en todo momento. Puedes ubicar manos cruzadas en el pecho o hacia arriba para mayor intensidad',
  'crunches_en_balon_nombre': 'Crunches en balón',
  'crunches_en_balon_descripcion': 'Ejercicio que trabaja principalmente el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'crunches_en_balon_paso1': 'Acostado boca arriba sobre balón, rodillas flexionadas, pies en el suelo, manos detrás de la cabeza',
  'crunches_en_balon_paso2': 'Elevar el tronco, curvando levemente la espalda, sin mover la cabeza hacia adelante y evitando el balanceo sobre el balón',
  'crunches_en_balon_paso3': 'Descender controladamente el tronco hasta regresar a la posición inicial',
  'crunches_en_balon_tips1': 'Puedes ubicar las manos cruzadas sobre el pecho o hacia adelante (recomendado para principiantes)',
  'crunches_en_balon_tips2': 'Evita el impulso con brazos o espalda y mantén los pies fijos en una posición en el suelo',
  'crunches_en_maquina_nombre': 'Crunches en máquina',
  'crunches_en_maquina_descripcion': 'Ejercicio que trabaja principalmente el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'crunches_en_maquina_paso1': 'Sentado en máquina abdominal, pies bajo el sopote frontal, manos en barras a cada costado',
  'crunches_en_maquina_paso2': 'Realizar una contracción abdominal, llevando el tronco hacia adelante y pies hacia arriba',
  'crunches_en_maquina_paso3': 'Regresar a la posición inicial controládamente, llevando el tronco atrás y pies abajo',
  'crunches_en_maquina_tips1': 'Mantén la espalda pegada a la silla, ayudado por los brazos en barras laterales y pies en el soporte frontal',
  'crunches_en_maquina_tips2': 'Procura realizar una isometría al juntar tronco con piernas por 1-2 segundos, para dar estímulo extra al abdomen',
  'crunches_en_v_nombre': 'Crunches en V',
  'crunches_en_v_descripcion': 'Variante de la abdominal básica, elevando las piernas y muslos, enfocando más el esfuerzo en la zona baja del recto abdominal.',
  'crunches_en_v_paso1': 'Acostado boca arriba, rodillas estiradas, brazos estirados sobre la cabeza',
  'crunches_en_v_paso2': 'Elevar el tronco y las piernas, manteniendo brazos y rodillas estiradas, hasta tocar los pies con las manos',
  'crunches_en_v_paso3': 'Descender controladamente tronco y piernas, hasta volver a la posición inicial',
  'crunches_en_v_tips1': 'Los brazos estirados y llevarlos adelante permiten ejecutar el ejercicio con mayor facilidad',
  'crunches_en_v_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'crunches_invertidos_nombre': 'Crunches invertidos',
  'crunches_invertidos_descripcion': 'Variante de la abdominal básica, elevando las piernas y muslos, enfocando más el esfuerzo en la zona baja del recto abdominal.',
  'crunches_invertidos_paso1': 'Acostado boca arriba, rodillas estiradas o levemente flexionadas, manos a los lados',
  'crunches_invertidos_paso2': 'Elevar las piernas hasta un ángulo mayor a 45Â°, levantando controladamente la cadera',
  'crunches_invertidos_paso3': 'Descender controladamente las piernas sin tocar el suelo con los talones',
  'crunches_invertidos_tips1': 'Ubica las manos a los lados bajo la cadera o colchonera, para brindar apoyo extra a la espalda',
  'crunches_invertidos_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'crunches_invertidos_en_banco_inclinado_nombre': 'Crunches invertidos en banco inclinado',
  'crunches_invertidos_en_banco_inclinado_descripcion': 'Variante de la abdominal básica, elevando las piernas y muslos, enfocando más el esfuerzo en la zona baja del recto abdominal.',
  'crunches_invertidos_en_banco_inclinado_paso1': 'Acostado boca arriba en banco inclinado, rodillas estiradas o levemente flexionadas, manos en barra sobre la cabeza o a cada lado superior del banco',
  'crunches_invertidos_en_banco_inclinado_paso2': 'Elevar las piernas hasta un ángulo mayor a 45Â°, levantando controladamente la cadera',
  'crunches_invertidos_en_banco_inclinado_paso3': 'Descender controladamente las piernas sin tocar el suelo con los talones, hasta posición inicial',
  'crunches_invertidos_en_banco_inclinado_tips1': 'Evita levantar la cadera al bajar las piernas, para evitar impulso y posibles molestas en la zona lumbar',
  'crunches_invertidos_en_banco_inclinado_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'crunches_laterales_nombre': 'Crunches laterales',
  'crunches_laterales_descripcion': 'Ejercicio que trabaja principalmente los oblicuos y zona lateral del abdomen, así como en menor medida el recto abdominal.',
  'crunches_laterales_paso1': 'Acostado boca arriba, rodillas flexionadas, piernas recostadas hacia un lado, manos al lado de la cabeza',
  'crunches_laterales_paso2': 'Elevar el tronco, curvando levemente la espalda y sin mover la cabeza hacia adelante',
  'crunches_laterales_paso3': 'Descender controladamente el tronca hasta regresar a la posición inicial',
  'crunches_laterales_paso4': 'Al finalizar la serie, llevar las piernas hacia el otro lado y ejecutar el mismo movimiento',
  'crunches_laterales_tips1': 'Puedes ubicar las manos cruzadas sobre el pecho o hacia adelante (recomendado para principiantes)',
  'crunches_laterales_tips2': 'Busca mantener las piernas fijas en el suelo o posición lateral y realiza muchas repeticiones para mayor intensidad muscular',
  'dominadas_nombre': 'Dominadas',
  'dominadas_descripcion': 'Ejercicio básico para la espalda. Excelente para desarrollar todo el conjunto de musculos, especialmente los dorsales y la expansión toráxica. Solicita en menor medida el bíceps braquial, supinador largo y pectoral mayor.',
  'dominadas_paso1': 'En suspensión en barra fija, manos con amplia separación y agarre en pronación.',
  'dominadas_paso2': 'Elevar el cuerpo (realizar una tracción), llevando el pecho hacia la barra superior',
  'dominadas_paso3': 'Descender el cuerpo suavemente, hasta extender los brazos y regresar a la posición inicial.',
  'dominadas_tips1': 'Puedes realizar una leve contracción al ascender, promoviendo el volumen de la espalda',
  'dominadas_tips2': 'Evita el impulso con las piernas y enfoca tu esfuerzo en trabajar inicialmente la técnica',
  'dominadas_tips3': 'Realiza un movimiento a velcidad lenta o media para un mejor trabajo en la espalda',
  'dominadas_asistidas_nombre': 'Dominadas Asistidas',
  'dominadas_asistidas_descripcion': 'Ejercicio básico para la espalda, con asistencia en máquina. Excelente para desarrollar todo el conjunto de musculos, especialmente los dorsales y la expansión toráxica. Solicita en menor medida el bíceps braquial, supinador largo y pectoral mayor.',
  'dominadas_asistidas_paso1': 'En suspensión, con manos en barra fija con amplia separación y agarre en pronación.',
  'dominadas_asistidas_paso2': 'Pies o rodillas sobre el soporte (en máquina asistida), mano como se indica en paso 1',
  'dominadas_asistidas_paso3': 'Elevar el cuerpo (realizar una tracción), llevando el pecho hacia la barra superior',
  'dominadas_asistidas_paso4': 'Descender el cuerpo suavemente, hasta extender los brazos y regresar a la posición inicial.',
  'dominadas_asistidas_tips1': 'Puedes realizar una leve contracción al ascender, promoviendo el volumen de la espalda',
  'dominadas_asistidas_tips2': 'Ubica un peso en la máquina adecuado (que descargue suavemente al estar sobre ella), para ganar fuerza al comenzar',
  'dominadas_asistidas_tips3': 'Realiza un movimiento a velocidad lenta o media para un mejor trabajo en la espalda',
  'elevacion_de_cadera_con_peso_nombre': 'Elevación de cadera con peso',
  'elevacion_de_cadera_con_peso_descripcion': 'Ejercicio de musculación, especialmente de los isquiotibiales y gluteos, para trabajar resistencia muscular y fortalecimiento de esta zona, así como abdomen y cintura',
  'elevacion_de_cadera_con_peso_paso1': 'Acostado boca arriba, apoyando la espalda en banco plano/step y pies juntos en el suelo o sobre step',
  'elevacion_de_cadera_con_peso_paso2': 'Ubicar la barra sobre la parte inferior del abdomen o sobre gluteos y elevar la cadera (posición inicial)',
  'elevacion_de_cadera_con_peso_paso3': 'Contrayendo el abdomen e inhalando fuertemente, descender la cadera suavemente, hasta casi tocar el suelo con los gluteos',
  'elevacion_de_cadera_con_peso_paso4': 'Subir de nuevo la barra hasta regresar a la posición inicial y contrayendo 1-2 segundos al final del movimiento',
  'elevacion_de_cadera_con_peso_paso5': 'Al finalizar, ubicar los soportes en máquina Smith o apoyar los gluteos en el suelo (barra libre)',
  'elevacion_de_cadera_con_peso_tips1': 'Respira siempre vigorosamente, ayudando a contraer los musculos de la cintura y abdomen',
  'elevacion_de_cadera_con_peso_tips2': 'Inicia con pesos bajos-moderados, para ganar fuerza en los gluteos, isquiotibiales y mejorar la técnica',
  'elevacion_de_cadera_con_peso_tips3': 'Procura hacer una pausa (contracción) al elevar la barra, apretando la zona abdominal, gluteos y muslos',
  'elevacion_de_piernas_nombre': 'Elevación de piernas',
  'elevacion_de_piernas_descripcion': 'Ejercicio abdominal, para trabajo en el recto abdominal, especialmente en el corte inferior y oblicuos.',
  'elevacion_de_piernas_paso1': 'Descolgado en máquina específica, antebrazos apoyados a cada lado y piernas estiradas',
  'elevacion_de_piernas_paso2': 'Manteniendo la espalda en el respaldo, elevar hacia al frente las piernas flexionadas o estiradas, hasta el abdomen',
  'elevacion_de_piernas_paso3': 'Descender las piernas, regresando a la posición inicial',
  'elevacion_de_piernas_tips1': 'Mantenga contraido el abdomen todo el tiempo, así como lograr contracciones en los oblicuos al elevar las piernas',
  'elevacion_de_piernas_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'elevacion_de_piernas_tips3': 'Variante con piernas extendidas o unipodal (subir una pierna a la vez) ayuda a brindar estímulo e intensidad variada al entrenamiento',
  'elevacion_de_piernas_cadera_acostado_nombre': 'Elevación de piernas-cadera acostado',
  'elevacion_de_piernas_cadera_acostado_descripcion': 'Ejercicio abdominal, para trabajo en el recto abdominal, especialmente en el corte inferior y oblicuos.',
  'elevacion_de_piernas_cadera_acostado_paso1': 'Acostado boca arriba en colchoneta, manos a cada lado apoyadas en suelo o en borde de colchoneta',
  'elevacion_de_piernas_cadera_acostado_paso2': 'Elevar las piernas verticalmente y estiradas, levantar la cintura del suelo, llevando pies lo más alto posible',
  'elevacion_de_piernas_cadera_acostado_paso3': 'Manteniendo la espalda en el suelo, bajar la cintura hasta la colchoneta,, regresando a posición inicial',
  'elevacion_de_piernas_cadera_acostado_tips1': 'Mantenga contraido el abdomen todo el tiempo, así como lograr contracciones en los oblicuos al elevar las piernas',
  'elevacion_de_piernas_cadera_acostado_tips2': 'Ejercicio que permite trabajar el conjunto de musculos de la cintura, practicar la técnica y su correcta ejecución',
  'elevacion_talones_de_pie_nombre': 'Elevación talones de pie',
  'elevacion_talones_de_pie_descripcion': 'Ejercicio para trabajar en conjunto el grupo de musculos de los gemelos, compuesto por el tríceps sural (sóleo y gemelos interno y externo).',
  'elevacion_talones_de_pie_paso1': 'De pie, hombros bajo el soporte, puntas de pies sobre la barra o soporte inferior',
  'elevacion_talones_de_pie_paso2': 'Manos en soportes laterales, tobillos en flexión pasiva y rodillas levemente flexionadas.',
  'elevacion_talones_de_pie_paso3': 'Elevar los talones, realizando una extensión de los pies verticalmente',
  'elevacion_talones_de_pie_paso4': 'Sostener y descender el soporte controladamente.',
  'elevacion_talones_de_pie_tips1': 'Los gemelos reaccionan mejor a cargas moderadas-altas y repeticiones mayores a 15 hasta fatiga',
  'elevacion_talones_de_pie_tips2': 'Girando levemente los tobillos hacia los lados, puede solicitar más los cortes respectivos a los gemelos',
  'elevacion_talones_sentado_nombre': 'Elevación talones sentado',
  'elevacion_talones_sentado_descripcion': 'Ejercicio para trabajo de pantorrillas, enfocado en el sóleo (tríceps sural).',
  'elevacion_talones_sentado_paso1': 'Sentado, rodillas bajo el soporte, puntas de pies sobre la barra o soporte inferior',
  'elevacion_talones_sentado_paso2': 'Manos en soportes frontales y tobillos en flexión pasiva.',
  'elevacion_talones_sentado_paso3': 'Elevar los talones, realizando una extensión de los pies verticalmente',
  'elevacion_talones_sentado_paso4': 'Sostener y descender el soporte controladamente.',
  'elevacion_talones_sentado_tips1': 'Los gemelos reaccionan mejor a cargas moderadas-altas y repeticiones mayores a 15 hasta fatig',
  'elevacion_talones_sentado_tips2': 'Girando levemente los tobillos hacia los lados, puede solicitar más los cortes respectivos a los gemelos',
  'elevaciones_frontales_barra_nombre': 'Elevaciones frontales barra',
  'elevaciones_frontales_barra_descripcion': 'Este ejercicio enfoca el entrenamiento en el deltoides anterior y haz clavicular del pectoral (primarios), así como deltoides lateral y posterior (secundarios)',
  'elevaciones_frontales_barra_paso1': 'De pie, rodillas ligeramente flexionadas, barra sobre muslos con manos en pronación',
  'elevaciones_frontales_barra_paso2': 'Con espalda recta y abdomen contraido, elevar los brazos adelante hasta la altura de los ojos',
  'elevaciones_frontales_barra_paso3': 'Descender la barra suavemente hasta la posición inicial',
  'elevaciones_frontales_barra_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_frontales_barra_tips2': 'Pueden realizarse variantes en polea baja, dando la espalda a la máquina y con barra o lazo.',
  'elevaciones_frontales_barra_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas.',
  'elevaciones_frontales_mancuerna_nombre': 'Elevaciones frontales mancuerna',
  'elevaciones_frontales_mancuerna_descripcion': 'Este ejercicio enfoca el entrenamiento en el deltoides anterior y haz clavicular del pectoral (primarios), así como deltoides lateral y posterior (secundarios)',
  'elevaciones_frontales_mancuerna_paso1': 'De pie, rodillas ligeramente flexionadas, mancuernas sobre muslos con manos en pronación',
  'elevaciones_frontales_mancuerna_paso2': 'Con espalda recta y abdomen contraido, elevar los brazos adelante hasta la altura de los ojos',
  'elevaciones_frontales_mancuerna_paso3': 'Descender las mancuernas suavemente hasta la posición inicial',
  'elevaciones_frontales_mancuerna_tips1': 'Puede realizar este ejercicio elevando las mancuernas al tiempo o unilateralmente (una a la vez)',
  'elevaciones_frontales_mancuerna_tips2': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_frontales_mancuerna_tips3': 'Pueden realizarse variantes en polea baja, dando la espalda a la máquina y con barra o lazo.',
  'elevaciones_frontales_mancuerna_tips4': 'Series con largas repeticiones son más recomendadas que con grandes cargas.',
  'elevaciones_frontales_polea_nombre': 'Elevaciones frontales Polea',
  'elevaciones_frontales_polea_descripcion': 'Este ejercicio enfoca el entrenamiento en el deltoides anterior y haz clavicular del pectoral (primarios), así como deltoides lateral y posterior (secundarios)',
  'elevaciones_frontales_polea_paso1': 'De pie, rodillas ligeramente flexionadas barra/mancuernas sobre muslos con manos en pronación',
  'elevaciones_frontales_polea_paso2': 'Con espalda recta y abdomen contraido, elevar los brazos adelante hasta la altura de los ojos',
  'elevaciones_frontales_polea_paso3': 'Descender la barra/mancuernas suavemente hasta la posición inicial',
  'elevaciones_frontales_polea_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_frontales_polea_tips2': 'Pueden realizarse variantes en polea baja, dando la espalda a la máquina y con barra o lazo.',
  'elevaciones_frontales_polea_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas.',
  'elevaciones_frontales_polea_unilateral_nombre': 'Elevaciones frontales polea unilateral',
  'elevaciones_frontales_polea_unilateral_descripcion': 'Este ejercicio enfoca el entrenamiento en el deltoides anterior y haz clavicular del pectoral (primarios), así como deltoides lateral y posterior (secundarios)',
  'elevaciones_frontales_polea_unilateral_paso1': 'De pie de espaldas a la polea, rodillas ligeramente flexionadas, tomar con una mano la barra de la polea baja en pronación',
  'elevaciones_frontales_polea_unilateral_paso2': 'Con espalda recta, abdomen contraido y brazo levemente flexionado, elevar el brazo adelante hasta la altura del hombro',
  'elevaciones_frontales_polea_unilateral_paso3': 'Descender la barra suavemente hasta el nivel de los muslos.',
  'elevaciones_frontales_polea_unilateral_paso4': 'Bajar la polea al finalizar la serie y realizar el mismo movimiento con el brazo contrario',
  'elevaciones_frontales_polea_unilateral_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_frontales_polea_unilateral_tips2': 'Series con largas repeticiones son más recomendadas que con grandes cargas.',
  'elevaciones_laterales_mancuerna_nombre': 'Elevaciones laterales Mancuerna',
  'elevaciones_laterales_mancuerna_descripcion': 'Ejercicio que solicita principalmente el deltoides medio (lateral), el cual, por su forma, se debe trabajar con mancuernas desde detrás de los gluteos, a los lados o delante de las piernas.',
  'elevaciones_laterales_mancuerna_paso1': 'De pie, rodillas ligeramente flexionadas mancuernas sobre muslos a los lados',
  'elevaciones_laterales_mancuerna_paso2': 'Con espalda recta y abdomen contraido, elevar los brazos a los lados hasta la altura de los hombros',
  'elevaciones_laterales_mancuerna_paso3': 'Descender las mancuernas suavemente hasta la posición inicial',
  'elevaciones_laterales_mancuerna_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_laterales_mancuerna_tips2': 'Pueden realizarse variante en máquina específica de vuelos laterales',
  'elevaciones_laterales_mancuerna_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas',
  'elevaciones_laterales_maquina_nombre': 'Elevaciones laterales Máquina',
  'elevaciones_laterales_maquina_descripcion': 'Ejercicio que solicita principalmente el deltoides medio (lateral), el cual, por su forma, se debe trabajar con mancuernas desde detrás de los gluteos, a los lados o delante de las piernas.',
  'elevaciones_laterales_maquina_paso1': 'Sentado, pecho o espalda apoyado(a) sobre respaldo frontal (espaldar), brazos bajo las barras laterales',
  'elevaciones_laterales_maquina_paso2': 'Con espalda recta y abdomen contraido, elevar los brazos a los lados hasta la altura de los hombros',
  'elevaciones_laterales_maquina_paso3': 'Descender las barras laterales suavemente hasta la posición inicial',
  'elevaciones_laterales_maquina_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_laterales_maquina_tips2': 'Pueden realizarse variante en máquina específica de vuelos laterales',
  'elevaciones_laterales_maquina_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas',
  'elevaciones_laterales_unilateral_nombre': 'Elevaciones laterales Unilateral',
  'elevaciones_laterales_unilateral_descripcion': 'Ejercicio que solicita principalmente el deltoides medio (lateral), el cual, por su forma, se debe trabajar con mancuernas desde detrás de los gluteos, a los lados o delante de las piernas.',
  'elevaciones_laterales_unilateral_paso1': 'De pie con rodillas levemente flexionadas junto a polea baja, tomar el soporte en pronación, con brazo contrario',
  'elevaciones_laterales_unilateral_paso2': 'Elevar la polea lateralmente, pasando la polea por delante o detrás del cuerpo (mayor dificultad)',
  'elevaciones_laterales_unilateral_paso3': 'Descender la polea al nivel de los muslos y bajarla al finalizar la serie',
  'elevaciones_laterales_unilateral_paso4': 'Realizar el mismo movimiento con el brazo contrario',
  'elevaciones_laterales_unilateral_tips1': 'Mantén la espalda recta y firme, evitando el impulso hacia atrás lo más posible',
  'elevaciones_laterales_unilateral_tips2': 'Puedes lograr mayor estabilidad ubicando el otro brazo en la cintura o en soporte de la máquina',
  'elevaciones_laterales_unilateral_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas',
  'elevaciones_posteriores_mancuerna_nombre': 'Elevaciones posteriores mancuerna',
  'elevaciones_posteriores_mancuerna_descripcion': 'Ejercicio para trabajar principalmente el deltoides posterior, el trapecio y los romboides (primarios), así como el resto del deltoides (secundarios).',
  'elevaciones_posteriores_mancuerna_paso1': 'De pie, tronco flexionado hacia adelante, mancuernas en cada mano y brazos descolgados adelante',
  'elevaciones_posteriores_mancuerna_paso2': 'Manteniendo las rodillas levemente flexionadas, elevar los brazos hacia los lados (ligéramente adelante), hasta la altura del tronco',
  'elevaciones_posteriores_mancuerna_paso3': 'Descender los brazos hacia al frente, regresando a la posición inicial',
  'elevaciones_posteriores_mancuerna_tips1': 'Evita el impulso con la espalda y zona lumbar, para reducir posibles molestias y enfocar el trabajo en el hombro',
  'elevaciones_posteriores_mancuerna_tips2': 'Puedes acostarte boca abajo sobre banco inclinado o ubicar la frente en un soporte, para reducir el impulso, así como ejecutar el ejercicio sentado en un banco',
  'elevaciones_posteriores_mancuerna_tips3': 'Puede realizar una contracción al abrir los brazos, para enfocar el deltoides posterior',
  'elevaciones_posteriores_mancuerna_tips4': 'Series con largas repeticiones y peso bjo-medio son más recomendadas que manejar grandes cargas',
  'encogimientos_nombre': 'Encogimientos',
  'encogimientos_descripcion': 'Ejercicio de trabajo en el trapecio, manteniendo los brazos semi estirados y con una leve contracción al subir los hombros.',
  'encogimientos_paso1': 'Sentado (apoyado sobre el espaldar) o de pie (rodillas semi flexionadas), mancuernas a ambos lados',
  'encogimientos_paso2': 'Manteniendo espalda recta, elevar los hombros, haciendo una contracción del trapecio en la parte superior',
  'encogimientos_paso3': 'Descender los hombros suavemente hasta la posición inicial',
  'encogimientos_tips1': 'Mantén la espalda recta y firme, sea al estar sentado o de pie.',
  'encogimientos_tips2': 'Realiza una contracción por 2-3 segundos, para brindar mayor esfuerzo al ejercicio',
  'espalda':'Espalda',
  'extension_codo_nombre': 'Extensión codo',
  'extension_codo_descripcion': 'Excelente ejercicio para congestionar el conjunto de los tríceps, buscando series largas para mayor trabajo',
  'extension_codo_paso1': 'De pie, piernas ligeramente flexionadas, tronco inclinado hacia adelante con espalda recta ',
  'extension_codo_paso2': 'Brazo en horizontal paralelo al cuerpo, pierna contraria adelante o mano-rodilla contraria sobre banco',
  'extension_codo_paso3': 'Sosteniendo la mancuerna en semi-pronación, extender el codo hacia atrás',
  'extension_codo_paso4': 'Descender la mancuerna, regresando a la posición inicial',
  'extension_codo_tips1': 'Se puede hacer una variante, ubicando una polea en la parte baja del soporte',
  'extension_codo_tips2': 'Una contracción al extender el codo es válida para dar mayor esfuerzo al ejercicio',
  'extension_codos_acostado_nombre': 'Extensión codos acostado',
  'extension_codos_acostado_descripcion': 'Excelente ejercicio básico para el desarrollo muscular en el tríceps, solicitando las tres porciones del mismo.',
  'extension_codos_acostado_paso1': 'Acostado boca arriba en banco plano, antebrazos flexionados, brazos verticales y mancuernas en cada mano, agarre el semi-pronación',
  'extension_codos_acostado_paso2': 'Flexionar los brazos (desdender las mancuernas) hacia cada lado o detrás de la cabeza',
  'extension_codos_acostado_paso3': 'Subir las mancuernas extendiendo los brazos, regresando a la posición inicial',
  'extension_codos_acostado_tips1': 'Excelente ejercicio para volumen y tonificación del tríceps',
  'extension_codos_acostado_tips2': 'La variante con mancuerna permite el control independiente del peso y mayor enfoque a cada brazo',
  'extension_codos_sentado_nombre': 'Extensión codos sentado',
  'extension_codos_sentado_descripcion': 'Ejercicio para el trabajo del tríceps (tanto porción larga, como vasto externo). El movimiento permite solicitar el musculo durante la contracción.',
  'extension_codos_sentado_paso1': 'Sentado con ambas manos sobre barra en pronación, detrás de la nuca',
  'extension_codos_sentado_paso2': 'Elevar la barra, extendiendo los brazos hacia arriba',
  'extension_codos_sentado_paso3': 'Descender la barra hasta regresar la posición inicial',
  'extension_codos_sentado_tips1': 'Mantén la espalda y cintura pegados al espaldar de la silla (contrae el abdomen)',
  'extension_codos_sentado_tips2': 'Busca realizar la extensión completa del tríceps y realizar una contracción al subir la barra, para mayor esfuerzo',
  'extension_de_rodilla_nombre': 'Extensión de rodilla',
  'extension_de_rodilla_descripcion': 'Mejor ejercicio para aislamiento de los cuádriceps. Recomendado para principiantes, para fortalecimiento de rodillas y musculos propios para otros ejercicios más técnicos.',
  'extension_de_rodilla_paso1': 'Sentado, pies bajo el soporte al ancho de hombros, manos en soportes laterales y espalda en respaldo.',
  'extension_de_rodilla_paso2': 'Extender las rodillas hasta la horizontal, manteniendo la espalda firme.',
  'extension_de_rodilla_paso3': 'Flexionar las rodillas, regresando a la posición inicial y evitando levantar los gluteos de la silla',
  'extension_de_rodilla_tips1': 'Trabaja los cuadriceps y realizar una contracción al extender las rodillas para mayor esfuerzo',
  'extension_de_rodilla_tips2': 'Iniciar con cargas bajas- moderadas para calentar y fortalecer las rodillas.',
  'face_pull_nombre': 'Face-Pull',
  'face_pull_descripcion': 'Ejercicio para trabajar principalmente el deltoides posterior, el trapecio y los romboides (primarios), así como el resto del deltoides (secundarios).',
  'face_pull_paso1': 'De pie, frente a la polea alta con lazo, manos con agarre en pronación y rodillas semi-flexionadas',
  'face_pull_paso2': 'Jalar el lazo hacia cada lado de la cabeza, manteniendo los codos altos y manos firmes',
  'face_pull_paso3': 'Estirar de nuevo los brazos hacia adelante, regresando a la posición inicial',
  'face_pull_tips1': 'Mantén la espalda recta y piernas firmes al suelo, así como los codos lo más alto posible',
  'face_pull_tips2': 'Puede realizar una contracción jalar el lazo hacia atrás, para enfocar el deltoides posterior',
  'face_pull_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas',
  'flexion_codo_curl_nombre': 'Flexión codo (Curl)',
  'flexion_codo_curl_descripcion': 'Ejercicio básico de musculación, para trabajar el bíceps braquial y braquial anterior (primarios). ',
  'flexion_codo_curl_paso1': 'De pie, espalda recta y rodillas levemente flexionadas.',
  'flexion_codo_curl_paso2': 'Tomar barra con agarre supino (palmas hacia al frente), levemente más ancho a los hombros.',
  'flexion_codo_curl_paso3': 'Subir la barra (flexionar los codos) hasta el nivel de la boca, procurando no impulsarse con la espalda',
  'flexion_codo_curl_paso4': 'Descender la barra, extendiendo los brazos y regresando a la posición inicial.',
  'flexion_codo_curl_tips1': 'Puede lograr mayor aislamiento del musculo, apoyando la espalda en la pared, manteniendo el movimiento constante.',
  'flexion_codo_curl_tips2': 'Separando más los brazos, solicita más la porción corta del bíceps y más juntas, la porción larga.',
  'flexion_codo_martillo_nombre': 'Flexión codo martillo',
  'flexion_codo_martillo_descripcion': 'Ejercicio apropiado para trabajar el supinador largo (antebrazo), bíceps y braquial anterior.',
  'flexion_codo_martillo_paso1': 'Sentado en predicador o de pie, tomar barra romana de soportes verticales(agarre neutro), ubicando discos a cada lado.',
  'flexion_codo_martillo_paso2': 'Subir la barra (flexionar los codos) hasta el nivel del pecho, evitando golpear el pecho.',
  'flexion_codo_martillo_paso3': 'Descender la barra hacia adelante, extendiendo los brazos y regresando a la posición inicial.',
  'flexion_codo_martillo_tips1': 'Variante para trabajar el bíceps, enfocando otros musculos como el supinador largo y braquial anterior ',
  'flexion_codo_martillo_tips2': 'Ejercicio apropiado para principiantes, para ganar fuerza en bíceps y antebrazo.',
  'flexion_de_rodilla_acostado_nombre': 'Flexión de rodilla acostado',
  'flexion_de_rodilla_acostado_descripcion': 'Ejercicio para trabajar específicamente musculos isquiotibiales (primario, con pies en extensión) y gemelos (con pies en flexión dorsal) en menor medida. ',
  'flexion_de_rodilla_acostado_paso1': 'Acostado boca abajo, piernas extendidas, tobillos bajo el soporte y manos en soportes frontales',
  'flexion_de_rodilla_acostado_paso2': 'Flexionar ambas piernas, buscando tocar los muslos/gluteo con los talores',
  'flexion_de_rodilla_acostado_paso3': 'Extender de nuevo las rodillas hasta regresar a la pisición inicial',
  'flexion_de_rodilla_acostado_tips1': 'Trabaja los isquiotibiales y se puede realizar unilateral (o en máquina para una pierna)',
  'flexion_de_rodilla_acostado_tips2': 'Iniciar con cargas bajas- moderadas para calentar y fortalecer las rodillas.',
  'flexion_de_rodilla_sentado_nombre': 'Flexión de rodilla sentado',
  'flexion_de_rodilla_sentado_descripcion': 'Ejercicio para trabajar específicamente musculos isquiotibiales (primario, con pies en extensión) y gemelos (con pies en flexión dorsal) en menor medida. ',
  'flexion_de_rodilla_sentado_paso1': 'Sentado, piernas extendidas apoyando talónes/gemelos sobre soporte frontal, manos a los lados o barra delantera',
  'flexion_de_rodilla_sentado_paso2': 'Flexionar ambas piernas, descendiendo el soporte frontal hasta formar ángulo de 90Â°',
  'flexion_de_rodilla_sentado_paso3': 'Extender de nuevo las rodillas hasta regresar a la pisición inicial',
  'flexion_de_rodilla_sentado_tips1': 'Trabaja los isquiotibiales y se puede realizar unilateral (o en máquina para una pierna) o acostado',
  'flexion_de_rodilla_sentado_tips2': 'Iniciar con cargas bajas- moderadas para calentar y fortalecer las rodillas, así como series largas para mayor intensidad en el entrenamiento.',
  'flexion_de_rodilla_unipodal_nombre': 'Flexión de rodilla unipodal',
  'flexion_de_rodilla_unipodal_descripcion': 'Ejercicio para trabajar específicamente musculos isquiotibiales (primario, con pies en extensión) y gemelos (con pies en flexión dorsal) en menor medida. ',
  'flexion_de_rodilla_unipodal_paso1': 'Acostado boca abajo, rodillas sobre soporte y pierna contraria bajo la barra posterior, manos en soportes frontales',
  'flexion_de_rodilla_unipodal_paso2': 'Flexionar la pierna, buscando tocar los muslos/gluteo con el talón',
  'flexion_de_rodilla_unipodal_paso3': 'Extender de nuevo la rodilla hasta regresar a la posición inicial',
  'flexion_de_rodilla_unipodal_paso4': 'Cambiar posición de ambas piernas y realizar el movimiento para el muslo contrario',
  'flexion_de_rodilla_unipodal_tips1': 'Trabaja los isquiotibiales y se puede realizar unilateral (o en máquina para una pierna)',
  'flexion_de_rodilla_unipodal_tips2': 'Iniciar con cargas bajas- moderadas para calentar y fortalecer las rodillas.',
  'flexiones_de_pecho_nombre': 'Flexiones de pecho',
  'flexiones_de_pecho_descripcion': 'Ejercicio básico para entrenar el pectoral mayor (primario) y tríceps (secundarios).',
  'flexiones_de_pecho_paso1': 'Acostado boca abajo en el suelo o sobre una colchoneta',
  'flexiones_de_pecho_paso2': 'Manos apoyadas a ambos lados, a la altura del pecho, un poco más abierto al ancho de los hombros',
  'flexiones_de_pecho_paso3': 'Extender los brazos hasta estirarlos, levantando el cuerpo y manteniendo la punta de pies apoyados en el suelo',
  'flexiones_de_pecho_paso4': 'Flexionar los brazos hasta tocar el suelo con el pecho, hasta volver a la posición inicial.',
  'flexiones_de_pecho_tips1': 'Es uno de los ejercicios básicos en musculación, excelente para ganar fuerza y resistencia',
  'flexiones_de_pecho_tips2': 'Para principiantes y mujeres, se recomiendo apoyar las rodillas, para ir ganando fuerza y técnica',
  'fondos_asistidos_nombre': 'Fondos asistidos',
  'fondos_asistidos_descripcion': 'Ejercicio para el desarrollo del volumen y tamaño del tríceps. Además de este grupo muscular, trabaja en menor medida los pectorales y los deltoides anteriores (parte frontal del hombro)',
  'fondos_asistidos_paso1': 'Manos sobre barras laterales, ubicar rodillas/pies sobre soporte frontal, estirar casi por completo los brazos',
  'fondos_asistidos_paso2': 'Flexionar los brazos, hasta los\n90Â°, manteniendo la espalda recta y la mirada al frente',
  'fondos_asistidos_paso3': 'Extender de nuevo los brazos casi por completo, hasta regresar a la posición inicial',
  'fondos_asistidos_tips1': 'Mantener la vista al frente y la espalda firme, para dar mayor esfuerzo al triíceps y evitar recargar los hombros',
  'fondos_asistidos_tips2': 'Para principiantes, se recomienda iniciar este ejercicio en máquina asistida, para ganar fuerza y técnica',
  'fondos_en_bancos_nombre': 'Fondos en bancos',
  'fondos_en_bancos_descripcion': 'Ejercicio para el desarrollo del volumen y tamaÃ±o del tríceps. Además de este grupo muscular, trabaja en menor medida los pectorales y los deltoides anteriores (parte frontal del hombro)',
  'fondos_en_bancos_paso1': 'Ubicar dos bancos planos de forma paralela, separados a suficiente distancia para ubicarse entre ellos',
  'fondos_en_bancos_paso2': 'Ubicar manos al borde de uno de ellos y los talones sobre el otro banco, estirar casi completo los brazos',
  'fondos_en_bancos_paso3': 'Flexionar los brazos, hasta los 90Â°, manteniendo la espalda recta y la mirada al frente',
  'fondos_en_bancos_paso4': 'Extender de nuevo los brazos casi por completo, hasta regresar a la posición inicial',
  'fondos_en_bancos_tips1': 'Mantener la vista al frente y la espalda firme, para dar mayor esfuerzo al tríceps y evitar recargar los hombros',
  'fondos_en_bancos_tips2': 'Para principiantes, se recomienda iniciar este ejercicio en máquina asistida, para ganar fuerza y técnica',
  'fondos_en_bancos_tips3': 'Para intermedios y avanzados, colocar peso sobre los muslos para lograr mayor intensidad en el ejercicio',
  'fondos_libres_nombre': 'Fondos libres',
  'fondos_libres_descripcion': 'Ejercicio para el desarrollo del volumen y tamaÃ±o del tríceps. Además de este grupo muscular, trabaja en menor medida los pectorales y los deltoides anteriores (parte frontal del hombro)',
  'fondos_libres_paso1': 'Manos sobre barras laterales, estirar casi por completo los brazos y descolgarse sobre la máquina',
  'fondos_libres_paso2': 'Flexionar los brazos, hasta los 90Â°, llevando levemente los pies hacia atrás',
  'fondos_libres_paso3': 'Extender de nuevo los brazos casi por completo, hasta regresar a la posición inicial',
  'fondos_libres_tips1': 'Mantener la vista al frente y la espalda firme, para dar mayor esfuerzo al tríceps y evitar recargar los hombros',
  'fondos_libres_tips2': 'Evitar balancear el cuerpo, buscando mantener firmes los brazos al realizar el movimiento',
  'fondos_libres_tips3': 'Para principiantes, se recomienda iniciar este ejercicio en máquina asistida, para ganar fuerza y técnica',
  'fondos_maquina_nombre': 'Fondos máquina',
  'fondos_maquina_descripcion': 'Ejercicio para el desarrollo del volumen y tamaÃ±o del tríceps. Además de este grupo muscular, trabaja en menor medida los pectorales y los deltoides anteriores (parte frontal del hombro)',
  'fondos_maquina_paso1': 'Sentado en la máquina, manos sobre barras laterales, estirar casi por completo los brazos',
  'fondos_maquina_paso2': 'Estirar casi por completo los brazos, logrando una contracción del tríceps',
  'fondos_maquina_paso3': 'Flexionar de nuevo los brazos, hasta regresar a la posición inicial',
  'fondos_maquina_tips1': 'Mantener la vista al frente y la espalda contra el respaldo, para dar mayor esfuerzo al tríceps y evitar recargar los hombros',
  'fondos_maquina_tips2': 'Para principiantes, realizar al menos 20 repeticiones de este ejercicio, para ganar fuerza y resistencia',
  'hombros':'Hombros',
  'home': 'Casa',
  'jalon_frontal_abierto_nombre': 'Jalón frontal abierto',
  'jalon_frontal_abierto_descripcion': 'Excelente ejercicio para desarrollar el grosor y la amplitud de la espalda, trabajando fibras superiores y centrales del dorsal ancho (primarios). Se solicitan en menor medida bíceps y trapecio.',
  'jalon_frontal_abierto_paso1': 'Sentado frente a la máquina hammer, manos separadas y con agarre en pronación en barras altas',
  'jalon_frontal_abierto_paso2': 'Ubicar piernas bajo el soporte y descender las barras por delante del rostro, hasta el nivel del pecho',
  'jalon_frontal_abierto_paso3': 'Ascender la barra (extender los brazos de nuevo), hasta volver a la posición inicial',
  'jalon_frontal_abierto_tips1': 'Puedes realizar una leve contracción al descender, promoviendo el volumen de la espalda',
  'jalon_frontal_abierto_tips2': 'Evita el impulso con la espalda, mantendiendo la espalda recta y firme',
  'jalon_frontal_abierto_tips3': 'Promueve la ganancia en fuerza y expansión dorsal.',
  'jalon_frontal_cerrado_agarre_neutro_nombre': 'Jalón frontal cerrado (agarre neutro)',
  'jalon_frontal_cerrado_agarre_neutro_descripcion': 'Excelente ejercicio para el desarrollo del dorsal ancho y redondo mayor, con participación menor del bíceps, braquial anterior, trapecio y los romboides.',
  'jalon_frontal_cerrado_agarre_neutro_paso1': 'Sentado frente a la máquina, manos en barra neutra y piernas bajo el soporte',
  'jalon_frontal_cerrado_agarre_neutro_paso2': 'Descender la barra hasta el nivel del pecho, inclinando ligeramente el tronco hacia atrás ',
  'jalon_frontal_cerrado_agarre_neutro_paso3': 'Ascender la barra (extender los brazos de nuevo), hasta volver a la posición inicial',
  'jalon_frontal_cerrado_agarre_neutro_tips1': 'Puedes realizar una leve contracción al descender, promoviendo el volumen de la espalda',
  'jalon_frontal_cerrado_agarre_neutro_tips2': 'Evita el impulso con la espalda, buscando que sea una inclinación leve hacia atrás',
  'jalon_frontal_cerrado_agarre_neutro_tips3': 'Promueve la ganancia en volumen y tamaÃ±o de los musculos de la espalda',
  'jalon_frontal_cerrado_supino_nombre': 'Jalón frontal cerrado (supino)',
  'jalon_frontal_cerrado_supino_descripcion': 'Excelente ejercicio para el desarrollo del dorsal ancho y redondo mayor, con participación menor del bíceps, braquial anterior, trapecio y los romboides.',
  'jalon_frontal_cerrado_supino_paso1': 'Sentado frente a la máquina, manos en supinación (palmas hacia el cuerpo) y piernas bajo el soporte',
  'jalon_frontal_cerrado_supino_paso2': 'Descender la barra hasta el nivel del pecho, inclinando ligeramente el tronco hacia atrás ',
  'jalon_frontal_cerrado_supino_paso3': 'Ascender la barra (extender los brazos de nuevo), hasta volver a la posición inicial',
  'jalon_frontal_cerrado_supino_tips1': 'Puedes realizar una leve contracción al descender, promoviendo el volumen de la espalda',
  'jalon_frontal_cerrado_supino_tips2': 'Evita el impulso con la espalda, buscando que sea una inclinación leve hacia atrás',
  'jalon_frontal_cerrado_supino_tips3': 'Promueve la ganancia en volumen y tamaÃ±o de los musculos de la espalda',
  'muslos':'Muslos',
  'pantorrillas':'Pantorrillas',
  'pecho':'Pecho',
  'peck_deck_nombre': 'Peck deck',
  'peck_deck_descripcion': 'Ejercicio para entrenar el pectoral mayor (primario), promoviendo la expansión toráxica y musculos pectorales.',
  'peck_deck_paso1': 'Sentado en la máquina, con los brazos separados en posición horizontal.',
  'peck_deck_paso2': 'Manos sobre soporte, codos levemente flexionados, antebrazos y muÃ±ecas firmes.',
  'peck_deck_paso3': 'Juntar los brazos, llevando las manos hacia al frente, sosteniendo levemente sin juntarlas. ',
  'peck_deck_paso4': 'Abrir de nuevo los brazos, hasta volver a la posición inicial.',
  'peck_deck_tips1': 'Permite en repeticiones largas lograr congestión sobre los pectorales, fomentando su crecimiento y amplitud.',
  'peck_deck_tips2': 'Recomendado para niveles principiante e intermedio, para ganar fuerza y técnica en el ejercicio. ',
  'peck_deck_invertido_nombre': 'Peck deck invertido',
  'peck_deck_invertido_descripcion': 'Ejercicio para trabajar principalmente el deltoides posterior, el trapecio y los romboides (primarios), así como el resto del deltoides (secundarios).',
  'peck_deck_invertido_paso1': 'Sentado de cara a la máquina, pecho sobre el respaldo, brazos al frente y manos en los agarres',
  'peck_deck_invertido_paso2': 'Abrir los brazos horizontalmente hacia los lados, buscando juntar los omoplatos',
  'peck_deck_invertido_paso3': 'Cerrar los brazos hacia al frente, regresando a la posición inicial',
  'peck_deck_invertido_tips1': 'Mantén la espalda recta y apoyando el pecho en el respaldo',
  'peck_deck_invertido_tips2': 'Puede realizar una contracción al abrir los brazos, para enfocar el deltoides posterior',
  'peck_deck_invertido_tips3': 'Series con largas repeticiones son más recomendadas que con grandes cargas',
  'peso_muerto_barra_nombre': 'Peso muerto barra',
  'peso_muerto_barra_descripcion': 'Uno de los movimientos básicos y más completos del culturismo y levantamiento de pesas. Trabaja, entre otros, cuádriceps, isquiotibiales, abductores y gluteos. En menor medida, conjunto de musculos de la espalda, bíceps y trapecio.',
  'peso_muerto_barra_paso1': 'De pie frente a la barra, piernas separadas y flexionadas hasta la horizontal, pies hacia al frente',
  'peso_muerto_barra_paso2': 'Tomar la barra con brazos estirados al ancho de los hombros, manos una en agarre supino y la otra en prono',
  'peso_muerto_barra_paso3': 'Inhalar, contener la respiración, contraer toda la zona abdominal y lumbar',
  'peso_muerto_barra_paso4': 'Tensar las piernas y enderezar el tronco hasta alcanzar la posición vertical.',
  'peso_muerto_barra_paso5': 'Descender controladamente la barra hasta casi tocar el suelo. Soltarla con cuidado al terminar la serie',
  'peso_muerto_barra_tips1': 'Procura realizar el movimiento completo, contrayendo en posición vertical por 1-2 segundos',
  'peso_muerto_barra_tips2': 'Iniciar con cargas bajas-moderadas para fortalecer los musculos entrenados y aprender la técnica correcta.',
  'peso_muerto_mancuerna_nombre': 'Peso muerto mancuerna',
  'peso_muerto_mancuerna_descripcion': 'Uno de los movimientos básicos y más completos del culturismo y levantamiento de pesas. Trabaja, entre otros, cuádriceps, isquiotibiales, abductores y gluteos. En menor medida, conjunto de musculos de la espalda, bíceps y trapecio.',
  'peso_muerto_mancuerna_paso1': 'De pie con mancuernas en cada mano y agarre en pronación, piernas separadas al ancho de los hombros, rodillas semi-flexionadas y pies hacia al frente',
  'peso_muerto_mancuerna_paso2': 'Inhalar e inclinar el tronco hacia adelante, manteniendo las rodillas levemente flexionadas y la mirada al frente',
  'peso_muerto_mancuerna_paso3': 'Descender las mancuernas hasta el nivel de los gemelos o tobillos (casi tocar el suelo), tronco firme y espalda recta',
  'peso_muerto_mancuerna_paso4': 'Ascender controladamente el tronco, hasta regresar a la posición inicial. Soltar con cuidado las mancuernas al terminar la serie',
  'peso_muerto_mancuerna_tips1': 'Procura realizar el movimiento completo, contrayendo en posición vertical por 1-2 segundos',
  'peso_muerto_mancuerna_tips2': 'Iniciar con cargas bajas-moderadas para fortalecer los musculos entrenados y aprender la técnica correcta.',
  'peso_muerto_mancuerna_unipodal_nombre': 'Peso muerto mancuerna unipodal',
  'peso_muerto_mancuerna_unipodal_descripcion': 'Movimiento alternativo al peso muerto. Trabaja, entre otros, cuádriceps, isquiotibiales, abductores y gluteos. En menor medida, conjunto de musculos de la espalda, bíceps y trapecio.',
  'peso_muerto_mancuerna_unipodal_paso1': 'De pie con mancuernas en cada mano y agarre en pronación, piernas separadas levemente menor al ancho de los hombros, rodillas semi-flexionadas y pies hacia al frente',
  'peso_muerto_mancuerna_unipodal_paso2': 'Inhalar e inclinar el tronco hacia adelante, elevando una pierna  estirada hacia atrás, rodilla frontal semi-flexionada',
  'peso_muerto_mancuerna_unipodal_paso3': 'Descender las mancuernas hasta el nivel de los gemelos o tobillos (casi tocar el suelo), tronco firme, mirada al frente y espalda recta',
  'peso_muerto_mancuerna_unipodal_paso4': 'Ascender controladamente el tronco, hasta regresar a la posición inicial. Realizar el mismo movimiento con pierna contraria al finalizar la serie.',
  'peso_muerto_mancuerna_unipodal_tips1': 'Procura realizar el movimiento completo, contrayendo en posición vertical por 1-2 segundos',
  'peso_muerto_mancuerna_unipodal_tips2': 'Iniciar con cargas bajas-moderadas para fortalecer los musculos entrenados y aprender la técnica correcta.',
  'planchas_nombre': 'Planchas',
  'planchas_descripcion': 'Uno de los ejercicios para trabajo abdominal más completos. Igualmente, permite solicitar otros musculos como cuádriceps, deltoides, tríceps, además de fomentar el equilibrio y coordinación',
  'planchas_paso1': 'Boca abajo, apoyando puntas de pies, codos, antebrazos y manos en el suelo/colchoneta',
  'planchas_paso2': 'Mantener posición de puente o plancha, respirando constantemente y contrayendo el abdomen',
  'planchas_paso3': 'Descender controladamente al sentir fatiga y/o quemazón en la zona abdominal',
  'planchas_tips1': 'Busca mantener la posición el mayor tiempo posible, contrayendo siempre el abdomen',
  'planchas_tips2': 'Mantén los hombros, codos y antebrazos lo más firme posible, para evitar presíón en ellos',
  'predicador_nombre': 'Predicador',
'predicador_descripcion': 'Uno de los mejores ejercicios para trabajar el bíceps braquial (primario), así como supinador largo y pronador redondo (secundarios). ',
  'predicador_paso1': 'Sentado en banco predicador máquina, brazos sobre soporte frontal.',
  'predicador_paso2': 'Tomar la barra frontal con agarre supino (palmas hacia al frente) o semi-neutro (segun ángulo del soporte)',
  'predicador_paso3': 'Subir la barra (flexionar los codos) hasta el nivel de la boca, procurando no despegar los gluteos de la silla',
  'predicador_paso4': 'Descender la barra, extendiendo los brazos y regresando a la posición inicial.',
  'predicador_tips1': 'Uno de los mejores ejercicios localizados para el bíceps. Mantén los gluteos sobre el banco y pies firmes al suelo.',
  'predicador_tips2': 'Es importante realizar un calentamiento previo, iniciando con cargas bajas y moderadas.',
  'prensa_horizontal_nombre': 'Prensa horizontal',
  'prensa_horizontal_descripcion': 'Ejercicio de musculación, especialmente de los cuádriceps (ubicando los pies en la parte baja de la plataforma), así como de gluteos e isquiotibiales (pies en parte alta de la plataforma).',
  'prensa_horizontal_paso1': 'Sentado en la máquina, espalda y cintura bien apoyados en repaldo, pies sobre plataforma al ancho de hombros',
  'prensa_horizontal_paso2': 'Ubicar las manos en soportes laterales y empujar la base, hasta estirar casi por completo las piernas',
  'prensa_horizontal_paso3': 'Flexionar las rodillas, llevando los muslos hacia las constillas, evitando levantar la cintura',
  'prensa_horizontal_paso4': 'Extender de nuevo las rodillas (casi por completo), hasta regresar a la posición inicial',
  'prensa_horizontal_tips1': 'Mantén la cintura y espalda siempre sobre el respaldo, ayudado por los brazos.',
  'prensa_horizontal_tips2': 'Pies juntos solicita más los cuadriceps, bien abiertos trabaja más los abductores (parte interna del muslo)',
  'prensa_inclinada_nombre': 'Prensa inclinada',
  'prensa_inclinada_descripcion': 'Ejercicio de musculación, especialmente de los cuádriceps (ubicando los pies en la parte baja de la plataforma), así como de gluteos e isquiotibiales (pies en parte alta de la plataforma).',
  'prensa_inclinada_paso1': 'Sentado en la máquina, espalda y cintura bien apoyados en repaldo, pies sobre plataforma al ancho de hombros',
  'prensa_inclinada_paso2': 'Empujar la base, retirar los seguros a los lados y ubicar las manos en soportes laterales',
  'prensa_inclinada_paso3': 'Flexionar las rodillas, llevando los muslos hacia las constillas, evitando levantar la cintura',
  'prensa_inclinada_paso4': 'Extender de nuevo las rodillas (casi por completo), hasta regresar a la posición inicial',
  'prensa_inclinada_tips1': 'Mantén la cintura y espalda siempre sobre el respaldo, ayudado por los brazos.',
  'prensa_inclinada_tips2': 'Pies juntos solicita más los cuadriceps, bien abiertos trabaja más los abductores (parte interna del muslo)',
  'press_arnold_nombre': 'Press Arnold',
  'press_arnold_descripcion': 'Ejercicio con rotación frontal de la muÃ±eca, el cual trabaja tanto deltoides lateral como anterior (primarios), así como trapecio, el haz clavicular del pectoral, el serrato mayor y el tríceps braquial (secundarios)',
  'press_arnold_paso1': 'Sentado, apoyando la espalda y cintura en el espaldar, mancuernas a la altura de los hombros',
  'press_arnold_paso2': 'Elevar las mancuernas verticalmente, extendiendo los brazos hacia arriba',
  'press_arnold_paso3': 'Descender las mancuernas hacia los hombros y luego, gritar los brazos hacia al frente uniendo mancuernas',
  'press_arnold_paso4': 'Manteniendo los brazos flexionados, abrir de nuevo los brazos a los lados a posición inicial',
  'press_arnold_tips1': 'Mantén la espalda recta y firme, apoyada sobre el respaldo',
  'press_arnold_tips2': 'Procura girar las mancuernas al nivel de la frente y no bajar los codos del nivel de los hombros',
  'press_declinado_nombre': 'Press declinado',
  'press_declinado_descripcion': 'Ejercicio básico para entrenar el corte inferior del pectoral mayor (primario), deltoides anterior y tríceps (secundarios).',
  'press_declinado_paso1': 'Acostado boca arriba sobre un banco declinado entre 20Â°-40Â° y pies apoyados en soporte.',
  'press_declinado_paso2': 'Manos en probación, brazos levemente flexionados sobre el tronco. (Posición inicial)',
  'press_declinado_paso3': 'Flexione los brazos, llevando las mancuernas hacia la zona baja del pecho, al lado del tronco.',
  'press_declinado_paso4': 'Extiende de nuevo los brazos, hasta volver a la posición inicial.',
  'press_declinado_tips1': 'Ubica las mancuernas sobre cada muslo antes de inicial el ejercicio, para mayor comodidad.',
  'press_declinado_tips2': 'Mantén la cintura apoyada sobre el banco, para evitar molestias en ésta zona.',
  'press_frontal_nombre': 'Press frontal',
  'press_frontal_descripcion': 'Ejercicio que enfoca el trabajo en los cortes anterior (codos hacia adelante) y lateral (codos separados) del deltoides, promoviendo el volumen y expansión muscular.',
  'press_frontal_paso1': 'Sentado, espalda apoyada en espaldar, barra con agarre en pronación, retirar la barra de los seguros',
  'press_frontal_paso2': 'Descender la barra frente a la cara hasta el nivel de la boca, flexionando los brazos, manteniendo la espalda y cintura apoyadas en el banco ',
  'press_frontal_paso3': 'Subir la barra hasta extendiendo los brazos y al finalizar la serie, ubicar los seguros para descargar',
  'press_frontal_tips1': 'Mantén la espalda y cintura apoyados en el espaldar, contrayendo el abdomen y enfocando el trabajo en los hombros',
  'press_frontal_tips2': 'Variación en máquina Smith o similares permite enfocar mejor el ejercicio en los deltoides',
  'press_hombro_nombre': 'Press hombro',
  'press_hombro_descripcion': 'Ejercicio para el volumen muscular, especialmente del deltoides lateral (primario), así como trapecio, serrato mayor y tríceps braquial (secundarios)',
  'press_hombro_paso1': 'Sentado, espalda apoyada en espaldar, mancuernas en pronación a la altura de los hombros',
  'press_hombro_paso2': 'Elevar las mancuernas, extendiendo los brazos verticalmente hasta estirarlos casi por completo',
  'press_hombro_paso3': 'Descender las mancuernas suavemente hasta la posición inicial',
  'press_hombro_tips1': 'Mantén la espalda y cintura apoyados en el espaldar, contrayendo el abdomen',
  'press_hombro_tips2': 'Puede realizar la variante a una mano, evitando inclinar el tronco hacia al lado contrario',
  'press_inclinado_nombre': 'Press inclinado',
  'press_inclinado_descripcion': 'Ejercicio básico para entrenar el corte superior del pectoral mayor (primario), deltoides anterior y tríceps (secundarios).',
  'press_inclinado_paso1': 'Sentado en banco inclinado (no mayor a 60Â°)',
  'press_inclinado_paso2': 'Mancuernas en pronación (agarre) y codos flexionados (Posición inicial)',
  'press_inclinado_paso3': 'Extiende los brazos verticalmente, hasta juntar las mancuernas.',
  'press_inclinado_paso4': 'Flexiona los brazos, hasta volver a la posición inicial.',
  'press_inclinado_tips1': 'Desciende las mancuernas hasta el nivel de la cabeza/pecho, sin golpearlo o rebotar con él.',
  'press_inclinado_tips2': 'Mantén un movimiento constante y los pies fijos en el soporte o el suelo',
  'press_plano_nombre': 'Press plano',
  'press_plano_descripcion': 'Ejercicio básico para entrenar el pectoral mayor (primario) y tríceps (secundarios).',
  'press_plano_paso1': 'Acostado boca arriba sobre un banco plano.',
  'press_plano_paso2': 'Manos en pronación separadas a una longitud levemente mayor al ancho de los hombros. (Posición inicial)',
  'press_plano_paso3': 'Flexiona los brazos, llevando las mancuernas hacia cada lado del tronco (zona media del pecho)',
  'press_plano_paso4': 'Extiende de nuevo los brazos, hasta volver a la posición inicial.',
  'press_plano_tips1': 'Es uno de los ejercicios básicos en musculación.',
  'press_plano_tips2': 'Excelente ejercicio para ganancia en fuerza, volumen muscular y definición.',
  'pull_over_nombre': 'Pull-over',
  'pull_over_descripcion': 'Ejercicio para entrenar el pectoral mayor (primario) y tríceps (secundarios), el cual promueve el crecimiento muscular y del torso.',
  'pull_over_paso1': 'Acostado boca arriba sobre un banco plano, pies apoyados en el suelo.',
  'pull_over_paso2': 'Mancuerna con agarre a dos manos (sobre el disco) y brazos extendidos (Posición inicial)',
  'pull_over_paso3': 'Baja la mancuerna por detrás de la cabeza, flexionando ligeramente los codos. ',
  'pull_over_paso4': 'Sube la mancuerna, regresando a la posición inicial.',
  'pull_over_tips1': 'Contrae el pecho al final del movimiento (promueve el volumen pectoral)',
  'pull_over_tips2': 'Desciende suavemente, llevando la mancuerna lo más atrás posible ',
  'push_down_nombre': 'Push-down',
  'push_down_descripcion': 'Ejercicio básico de aislamiento del tríceps, excelente para ganar fuerza para movimientos más complejos.',
  'push_down_paso1': 'De pie, frente a máquina de polea, manos en barra recta/diagonal, codos alineados al cuerpo',
  'push_down_paso2': 'Extender los codos (descender la polea) hasta nivel de los muslos',
  'push_down_paso3': 'Manteniendo codos cerca al cuerpo, ascender la polea a posición inicial',
  'push_down_tips1': 'La variación con lazo enfoca el trabajo más en el vasto externo del tríceps',
  'push_down_tips2': 'Puedes realizar una leve contracción isométrica al extender los codos, para brindar esfuerzo extra',
  'push_down_tips3': 'Variante con barra rexta permite una mayor concentración de la fuerza a todos los cortes del musculo',
  'remo_anclado_nombre': 'Remo anclado',
  'remo_anclado_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_anclado_paso1': 'Sentado frente a la máquina, pies sobre soportes\nfrontales, tronco apoyado en el soporte',
  'remo_anclado_paso2': 'Tomar las barras frontales en agarre semi prono,\npalmas ahcia abajo (o variante en neutro o supino)',
  'remo_anclado_paso3': 'Llevar las barras hacia cada costado del tronco,\nmanteniendo los codos casi pegados al cuerpo, hasta la zona del pectoral\ninferior',
  'remo_anclado_paso4': 'Volver las barras de nuevo hacia adelante\nsuavemente, extendiendo los brazos y regresando a la posición inicial',
  'remo_anclado_tips1': 'Evita llevar la espalda más atrás de los 90Â° al realizar el movimiento, para no lastimar la zona lumbar',
  'remo_anclado_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_anclado_tips3': 'Excelente ejercicio para aumentar el grosor de la espalda',
  'remo_barra_prono_nombre': 'Remo Barra (prono)',
  'remo_barra_prono_descripcion': 'Ejercicio básico, para el trabajo del dorsal ancho, el redondo mayor, corte posterior del deltoides, trapecio y romboides.',
  'remo_barra_prono_paso1': 'De pie, rodillas levemente flexionadas, manos en supinación (palmas hacia afuera) y levemente mayor a ancho de hombros ',
  'remo_barra_prono_paso2': 'Con cuerpo inclinado 45Â°, elevar la barra hasta la parte baja del pecho',
  'remo_barra_prono_paso3': 'Descender la barra, regresando a la posición inicial',
  'remo_barra_prono_tips1': '(Barra) Contrae el abdomen y mantén la respiración al elevar la barra',
  'remo_barra_prono_tips2': '(Barra) Evita el impulso con la espalda y mantén firme la zona abdominal y lumbar.',
  'remo_barra_prono_tips3': '(Mancuerna/barra) Estira lo más posible el brazo, para lograr mayor enfoque a la espalda',
  'remo_barra_supino_nombre': 'Remo Barra (supino)',
  'remo_barra_supino_descripcion': 'Ejercicio básico, para el trabajo del dorsal ancho, el redondo mayor, corte posterior del deltoides, trapecio y romboides.',
  'remo_barra_supino_paso1': 'De pie, rodillas levemente flexionadas, manos en pronación y levemente mayor a ancho de hombros ',
  'remo_barra_supino_paso2': 'Con cuerpo inclinado 45Â°, elevar la barra hasta la parte baja del pecho',
  'remo_barra_supino_paso3': 'Descender la barra, regresando a la posición inicial',
  'remo_barra_supino_tips1': '(Barra) Contrae el abdomen y mantén la respiración al elevar la barra',
  'remo_barra_supino_tips2': '(Barra) Evita el impulso con la espalda y mantén firme la zona abdominal y lumbar.',
  'remo_barra_supino_tips3': '(Mancuerna/barra) Estira lo más posible el brazo, para lograr mayor enfoque a la espalda',
  'remo_barra_t_maquina_nombre': 'Remo Barra T (máquina)',
  'remo_barra_t_maquina_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_barra_t_maquina_paso1': 'Pies sobre el soporte, tronco sobre el soporte frontal y manos en pronación en las barras frontales de la máquina',
  'remo_barra_t_maquina_paso2': 'Retirar la barra del apoyo y elevarla  hacia el esternón, llevando los discos hacia la zona pectoral y codos casi pegados al tronco',
  'remo_barra_t_maquina_paso3': 'Descender los discos suavemente, estirando los brazos y regresando a la posición inicial',
  'remo_barra_t_maquina_paso4': 'Al finalizar, ubicar la barra nuevamente sobre el apoyo',
  'remo_barra_t_maquina_tips1': 'Evita impulsarte con la espalda o lumbares, manteniendo el tronco en el soporte y sin empujarlo',
  'remo_barra_t_maquina_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_barra_t_maquina_tips3': 'Excelente ejercicio para aumentar el volumen y fortalecimiento general de la espalda',
  'remo_barra_t_neutro_nombre': 'Remo Barra T (neutro)',
  'remo_barra_t_neutro_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_barra_t_neutro_paso1': 'De pie, barra entre las piernas, barra V bajo la barra, tronco flexionado 45Â° y rodillas semi flexionadas',
  'remo_barra_t_neutro_paso2': 'Levantar la barra V hacia el esternón, llevando los discos hacia la zona pectoral y codos casi pegados al tronco',
  'remo_barra_t_neutro_paso3': 'Descender los discos suavemente, estirando los brazos y regresando a la posición inicial',
  'remo_barra_t_neutro_tips1': 'Evita impulsarte con la espalda o lumbares, para no lastimar o lesionar la zona lumbar',
  'remo_barra_t_neutro_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_barra_t_neutro_tips3': 'Excelente ejercicio para aumentar el volumen y fortalecimiento general de la espalda',
  'remo_erguido_nombre': 'Remo erguido',
  'remo_erguido_descripcion': 'Ejercicio complejo y uno de los más completos para hombro. Trabaja el conjunto de los deltoides, el trapecio, el bíceps, así como musculos de los antebrazos, gluteos y abdominales en menor medida.',
  'remo_erguido_paso1': 'De pie (piernas ligeramente separadas y semi flexionadas), barra/mancuernas sobre los muslos al frente',
  'remo_erguido_paso2': 'Manos en pronación y al ancho de los hombros, espalda recta y firme ',
  'remo_erguido_paso3': 'Elevar la barra/mancuernas cerca al cuerpo, hasta el nivel del mentón',
  'remo_erguido_paso4': 'Descender controladamente la barra/mancuernas a la posición inicial ',
  'remo_erguido_tips1': 'Mantén la espalda recta y firme, evitando el impulso con la zona lumbar y la inclinación adelante.',
  'remo_erguido_tips2': 'Realiza una contracción por 1-2 segundos al subir, para brindar mayor esfuerzo al ejercicio',
  'remo_mancuerna_nombre': 'Remo mancuerna',
  'remo_mancuerna_descripcion': 'Ejercicio básico, para el trabajo del dorsal ancho, el redondo mayor, corte posterior del deltoides, trapecio y romboides.',
  'remo_mancuerna_paso1': '(Mancuerna) Ubicar mano y rodilla sobre banco plano y mano opuesta con mancuerna (semi-pronació)',
  'remo_mancuerna_paso2': '(Mancuerna) Espalda recta y firme, elevar la mancuerna al nivel del pecho, brazo paralelo al cuerpo ',
  'remo_mancuerna_paso3': '(Mancuerna) Descender la mancuerna, regresando a la posición inicial',
  'remo_mancuerna_tips1': '(Barra) Contrae el abdomen y mantén la respiración al elevar la barra',
  'remo_mancuerna_tips2': '(Barra) Evita el impulso con la espalda y mantén firme la zona abdominal y lumbar.',
  'remo_mancuerna_tips3': '(Mancuerna/barra) Estira lo más posible el brazo, para lograr mayor enfoque a la espalda',
  'remo_mancuerna_tips4': 'Puedes realizar este ejercicio con mancuernas en ambas manos, para ganar resistencia y potencia muscular',
  'remo_polea_bajo_barra_v_nombre': 'Remo polea bajo (Barra V)',
  'remo_polea_bajo_barra_v_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_polea_bajo_barra_v_paso1': 'Sentado frente a la máquina, pies sobre soportes frontales, tronco flexionado',
  'remo_polea_bajo_barra_v_paso2': 'Tomar la barra V (agarre neutro), llevarla hacia la zona del esternón',
  'remo_polea_bajo_barra_v_paso3': 'Mantener los codos hacia atrás y hasta enderezar la espalda',
  'remo_polea_bajo_barra_v_paso4': 'Llevar la barra de nuevo hacia adelante suavemente, flexionando levemente el tronco adelante',
  'remo_polea_bajo_barra_v_tips1': 'Evita llevar la espalda hacia atrás al realizar el movimiento, para no lastimar la zona lumbar',
  'remo_polea_bajo_barra_v_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_polea_bajo_barra_v_tips3': 'Excelente ejercicio para aumentar el grosor de la espalda',
  'remo_polea_bajo_prono_nombre': 'Remo polea bajo (prono)',
  'remo_polea_bajo_prono_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_polea_bajo_prono_paso1': 'Sentado frente a la máquina, pies sobre soportes frontales, tronco flexionado',
  'remo_polea_bajo_prono_paso2': 'Tomar la barra recta (agarre prono, palmas ahcia abajo) al ancho o levemenenta más amplio de los hombros',
  'remo_polea_bajo_prono_paso3': 'Llevar la barra hacia la zona del esternón, manteniendo los codos casi pegados al cuerpo y hasta enderezar la espalda',
  'remo_polea_bajo_prono_paso4': 'Llevar la barra de nuevo hacia adelante suavemente, flexionando levemente el tronco adelante',
  'remo_polea_bajo_prono_tips1': 'Evita llevar la espalda más atrás de los 90Â° al realizar el movimiento, para no lastimar la zona lumbar',
  'remo_polea_bajo_prono_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_polea_bajo_prono_tips3': 'Excelente ejercicio para aumentar el grosor de la espalda',
  'remo_polea_bajo_supino_nombre': 'Remo polea bajo (supino)',
  'remo_polea_bajo_supino_descripcion': 'Ejercicio básico, excelente para desarrollar el grosor de la espalda, trabajando en conjunto dorsal ancho, redondo mayor, corte posterior del deltoides, bíceps, braquial anterior, trapecio y romboides.',
  'remo_polea_bajo_supino_paso1': 'Sentado frente a la máquina, pies sobre soportes frontales, tronco flexionado',
  'remo_polea_bajo_supino_paso2': 'Tomar la barra recta (agarre supino, palmas ahcia arriba) al ancho o levemenenta más amplio de los hombros',
  'remo_polea_bajo_supino_paso3': 'Llevar la barra hacia la zona del esternón, manteniendo los codos casi pegados al cuerpo y hasta enderezar la espalda',
  'remo_polea_bajo_supino_paso4': 'Llevar la barra de nuevo hacia adelante suavemente, flexionando levemente el tronco adelante',
  'remo_polea_bajo_supino_tips1': 'Evita llevar la espalda más atrás de los 90Â° al realizar el movimiento, para no lastimar la zona lumbar',
  'remo_polea_bajo_supino_tips2': 'Mantén una leve contracción al flexionar los brazos, manteniendo codos cerca al cuerpo',
  'remo_polea_bajo_supino_tips3': 'Excelente ejercicio para aumentar el grosor de la espalda',
  'sentadilla_frontal_nombre': 'Sentadilla frontal',
  'sentadilla_frontal_descripcion': 'Ejercicio alternativo a la sentadilla libre. Trabaja principalmente los cuádriceps, los gluteos, los abductores, los musculos extensores de la columna, los abdominales y los isquiotibiales.',
  'sentadilla_frontal_paso1': 'Barra sobre soporte, ubicarla sobre los hombros, en la parte alta del pecho. ',
  'sentadilla_frontal_paso2': 'Ubicar las manos sobre la barra en posición cómoda, manteniendo la barra en posición, codos adelante o manos cruzadas',
  'sentadilla_frontal_paso3': 'Retirar la barra, dar uno-dos pasos atrás, ubicando pies paralelos o levemente diagonales, al ancho de hombros',
  'sentadilla_frontal_paso4': 'Inhalar profundamente (contracción abdominal fuerte), flexionar las rodillas sin curvar la espalda adelante',
  'sentadilla_frontal_paso5': 'Cuando el fémur realice la horizontal con el suelo,  extender las rodillas para regresar a la posición inicial',
  'sentadilla_frontal_tips1': 'Promueve la fortaleza general del sistema muscular y adquirir buena capacidad torácica.',
  'sentadilla_frontal_tips2': 'Mejor ejercicio para trabajar los guteos y el conjunto de musculos de los muslos-cadera.',
  'sentadilla_frontal_tips3': 'Evita la inclinación hacia adelante y un movimiento de rebote al ascender, para evitar lesiones',
  'sentadilla_hack_nombre': 'Sentadilla Hack',
  'sentadilla_hack_descripcion': 'Ejercicio de musculación, especialmente de los cuádriceps (ubicando los pies en la parte baja de la plataforma), así como de gluteos e isquiotibiales (pies en parte alta de la plataforma).',
  'sentadilla_hack_paso1': 'Acostado en la máquina, espalda, cintura y hombros bien apoyados en repaldo, pies sobre plataforma al ancho de hombros',
  'sentadilla_hack_paso2': 'Ubicar las manos en soportes laterales y empujar la base hasta estirar casi por completo las piernas y retirar seguros.',
  'sentadilla_hack_paso3': 'Flexionar las rodillas hasta formar 90Â° con los muslos y la plataforma, evitando levantar la cintura',
  'sentadilla_hack_paso4': 'Extender de nuevo las rodillas (casi por completo), hasta regresar a la posición inicial',
  'sentadilla_hack_paso5': 'Al finalizar, poner los seguros y bajar la máquina suavemente',
  'sentadilla_hack_tips1': 'Mantén la cintura y espalda siempre sobre el respaldo, ayudado por los brazos y soportes laterales',
  'sentadilla_hack_tips2': 'Pies juntos solicita más los cuadriceps, bien abiertos trabaja más los abductores (parte interna del muslo)',
  'sentadilla_libre_nombre': 'Sentadilla libre',
  'sentadilla_libre_descripcion': 'Uno de los principales ejercicios de musculación en el culturismo y levantamiento de pesas. Trabaja principalmente los cuádriceps, los gluteos, los abductores, los musculos extensores de la columna, los abdominales y los isquiotibiales.',
  'sentadilla_libre_paso1': 'Barra sobre soporte, ubicarla sobre trapecio, un poco más alta a deltoides posteriores. ',
  'sentadilla_libre_paso2': 'Ubicar las manos sobre la barra en posición cómoda y mantener los codos hacia atrás',
  'sentadilla_libre_paso3': 'Retirar la barra, dar uno-dos pasos atrás, ubicando pies paralelos o levemente diagonales, al ancho de hombros',
  'sentadilla_libre_paso4': 'Inhalar profundamente (contracción abdominal fuerte), flexionar las rodillas sin curvar la espalda adelante',
  'sentadilla_libre_paso5': 'Cuando el fémur realice la horizontal con el suelo,  extender las rodillas para regresar a la posición incial',
  'sentadilla_libre_tips1': 'Promueve la fortaleza general del sistema muscular y adquirir buena capacidad torácica.',
  'sentadilla_libre_tips2': 'Mejor ejercicio para trabajar los guteos y el conjunto de musculos de los muslos-cadera.',
  'sentadilla_libre_tips3': 'Evita la inclinación hacia adelante y un movimiento de rebote al ascender, para evitar lesiones',
  'sentadilla_smith_nombre': 'Sentadilla Smith',
  'sentadilla_smith_descripcion': 'Uno de los principales ejercicios de musculación en el culturismo y levantamiento de pesas. Trabaja principalmente los cuádriceps, los gluteos, los abductores, los musculos extensores de la columna, los abdominales y los isquiotibiales.',
  'sentadilla_smith_paso1': 'Ubicarse bajo la barra, apoyándola sobre el trapecio, un poco más alta a deltoides posteriores. ',
  'sentadilla_smith_paso2': 'Ubicar las manos sobre la barra en posición cómoda y mantener los codos hacia atrás',
  'sentadilla_smith_paso3': 'Retirar la barra de los soportes, ubicando pies medio paso al frente, paralelos o levemente diagonales, al ancho de hombros',
  'sentadilla_smith_paso4': 'Inhalar profundamente (contracción abdominal fuerte), flexionar las rodillas sin curvar la espalda adelante',
  'sentadilla_smith_paso5': 'Cuando el fémur realice la horizontal con el suelo, extender las rodillas para regresar a la posición incial',
  'sentadilla_smith_tips1': 'Promueve la fortaleza general del sistema muscular y adquirir buena capacidad torácica.',
  'sentadilla_smith_tips2': 'Mejor ejercicio para trabajar los guteos y el conjunto de musculos de los muslos-cadera.',
  'sentadilla_smith_tips3': 'Evita la inclinación hacia adelante y un movimiento de rebote al ascender, para evitar lesiones',
  'sit_ups_nombre': 'Sit-ups',
  'sit_ups_descripcion': 'Ejercicio que trabaja principalmente el recto mayor abdominal, así como en menor medida los oblicuos (alternando codo-rodilla contraria).',
  'sit_ups_paso1': 'Acostado boca arriba, rodillas flexionadas, pies en el suelo, manos detrás de la cabeza',
  'sit_ups_paso2': 'Elevar el tronco casi por completo (despegando completamente la espalda del suelo), curvando levemente la espalda y sin mover la cabeza hacia adelante',
  'sit_ups_paso3': 'Descender controladamente el tronca hasta regresar a la posición inicial',
  'sit_ups_tips1': 'Puedes ubicar las manos cruzadas sobre el pecho o hacia adelante (recomendado para principiantes)',
  'sit_ups_tips2': 'Puedes levantar la punta de los pies y evita el impulso con brazos o espalda',
  'tijeras_nombre': 'Tijeras',
  'tijeras_descripcion': 'Ejercicio abdominal (elevación de piernas alterno), enfocando el esfuerzo en la zona baja del recto abdominal y en menor medida los oblícuos.',
  'tijeras_paso1': 'Acostado boca arriba, rodillas extendidas, manos a los lados apoyados en el suelo o en colchoneta y pies elevados',
  'tijeras_paso2': 'Con la cabeza apoyada en el suelo, levantar alternamente cada pierna hasta formar un ángulo de 45Â°',
  'tijeras_paso3': 'Realizar este movimiento, hasta finalizar las repeticiones establecidas (cada movimineto de ambas piernas es una repetición)',
  'tijeras_tips1': 'Mantenga contraido el abdomen todo el tiempo, así como lograr contracciones en los oblicuos al elevar el tronco',
  'tijeras_tips2': 'Realiza el movimiento hasta la sensación de quemazón en el abdomen',
  'tijeras_tips3': 'Busca no apoyar los pies en el suelo durante la ejecución del ejercicio',
  'triceps':'Tríceps',
  'warm_excercises': 'Ver ejercicios de calentamiento',
  'zancadas_nombre': 'Zancadas',
  'zancadas_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_paso1': 'De pie, piernas ligeramente separadas, barra sobre el trapecio y deltoides posterior',
  'zancadas_paso2': 'Realizar una zancada (paso largo adelante), manteniendo el tronco lo más recto posible',
  'zancadas_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_paso4': 'Extender la rodilla delantera y llevar la pierna posterior al nivel de la frontal',
  'zancadas_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_tips2': 'Variante con mancuernas en cada mano es válida.',
  'zancadas_barra_en_banco_nombre': 'Zancadas barra en banco',
  'zancadas_barra_en_banco_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_barra_en_banco_paso1': 'De pie, piernas ligeramente separadas, barra sobre el trapecio y deltoides posterior',
  'zancadas_barra_en_banco_paso2': 'Ubicar un pie en un banco o step por detrás del cuerpo, manteniendo el tronco lo más recto posible',
  'zancadas_barra_en_banco_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_barra_en_banco_paso4': 'Extender la rodilla delantera, manteniendo la pierna posterior sobre el banco o step',
  'zancadas_barra_en_banco_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_barra_en_banco_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_barra_en_banco_tips2': 'Ubicar el pie delantero más adelante, brinda mayor esfuerzo en los muslos de esta pierna.',
  'zancadas_en_smith_nombre': 'Zancadas en Smith',
  'zancadas_en_smith_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_en_smith_paso1': 'De pie, barra sobre el trapecio y deltoides posterior, un pie adelante y otro un paso atrás, apoyando la punta en el suelo',
  'zancadas_en_smith_paso2': 'Manteniendo el tronco lo más recto posible, retirar la barra del soporte',
  'zancadas_en_smith_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_en_smith_paso4': 'Extender la rodilla delantera y llevar la pierna posterior al nivel de la frontal',
  'zancadas_en_smith_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_en_smith_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_en_smith_tips2': 'Un paso más largo atrás, permite un mayor esfuerzo en los cuádriceps y gluteos de pierna frontal',
  'zancadas_en_smith_con_banco_nombre': 'Zancadas en Smith con banco',
  'zancadas_en_smith_con_banco_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_en_smith_con_banco_paso1': 'De pie, barra sobre el trapecio y deltoides posterior, un pie adelante y otro un paso atrás, apoyando la punta del pie sobre un banco o step',
  'zancadas_en_smith_con_banco_paso2': 'Manteniendo el tronco lo más recto posible, retirar la barra del soporte',
  'zancadas_en_smith_con_banco_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_en_smith_con_banco_paso4': 'Extender la rodilla delantera y llevar la pierna posterior al nivel de la frontal',
  'zancadas_en_smith_con_banco_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_en_smith_con_banco_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_en_smith_con_banco_tips2': 'Un paso más largo atrás, permite un mayor esfuerzo en los cuádriceps y gluteos de pierna frontal',
  'zancadas_mancuerna_nombre': 'Zancadas mancuerna',
  'zancadas_mancuerna_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_mancuerna_paso1': 'De pie, piernas ligeramente separadas, mancuernas en cada mano',
  'zancadas_mancuerna_paso2': 'Realizar una zancada (paso largo adelante), manteniendo el tronco lo más recto posible',
  'zancadas_mancuerna_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_mancuerna_paso4': 'Extender la rodilla delantera y llevar la pierna posterior al nivel de la frontal',
  'zancadas_mancuerna_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_mancuerna_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_mancuerna_tips2': 'Variante con mancuernas en cada mano es válida, realizando la serie con una pierna o de manera alterna.',
  'zancadas_mancuerna_en_banco_nombre': 'Zancadas mancuerna en banco',
  'zancadas_mancuerna_en_banco_descripcion': 'Este ejercicio trabaja intensamente los gluteos mayores, así como cuádriceps (pasos cortos) e isquiotibiales (pasos largos).',
  'zancadas_mancuerna_en_banco_paso1': 'De pie, piernas ligeramente separadas, mancuernas en cada mano a ambos lados del cuerpo',
  'zancadas_mancuerna_en_banco_paso2': 'Ubicar un pie en un banco o step por detrás del cuerpo, manteniendo el tronco lo más recto posible',
  'zancadas_mancuerna_en_banco_paso3': 'Descender la rodilla de la pierna posterior, hasta que muslo delantero forme la horizontal',
  'zancadas_mancuerna_en_banco_paso4': 'Extender la rodilla delantera, manteniendo la pierna posterior sobre el banco o step',
  'zancadas_mancuerna_en_banco_paso5': 'Realizar el mismo movimiento con la otra pierna, hasta completar las repeticiones establecidas',
  'zancadas_mancuerna_en_banco_tips1': 'Puede realizarse en posición fija y máquina, alternando la pierna que va hacia adelante y atrás.',
  'zancadas_mancuerna_en_banco_tips2': 'Ubicar el pie delantero más adelante, brinda mayor esfuerzo en los muslos de esta pierna.',
};
